import Head from 'next/head';
import { ReactElement, JSXElementConstructor, ReactFragment, ReactPortal } from 'react';
import styled from 'styled-components';

import Header from '../header/Header';

type layoutPropsType = {
  children: ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal;
};

function Layout(props: layoutPropsType) {
  return (
    <LayoutWrap>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>{props.children}</main>
    </LayoutWrap>
  );
}

export default Layout;

const LayoutWrap = styled.div`
  max-width: 1920px;
  margin: 0 auto;
`;
