import Head from "next/head";
import {
  ReactElement,
  JSXElementConstructor,
  ReactFragment,
  ReactPortal,
} from "react";

import Header from "../header/Header";
import RankCarousel from "../rankCarousel/RankCarousel";

type layoutPropsType = {
  children:
    | ReactElement<any, string | JSXElementConstructor<any>>
    | ReactFragment
    | ReactPortal;
};

function Layout(props: layoutPropsType) {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <RankCarousel />
      <main>{props.children}</main>
    </>
  );
}

export default Layout;
