export const NEW_ITEM_INFO = [
  {
    name: '캐쥬얼 남성 항공점퍼',
    price: 199000,
    modelImage: '/images/item/newitem/newitem1.png',
    itemImage: '/images/item/newitem/newitem1-1.png',
    imgHeight: 400,
  },
  {
    name: '항공점퍼 남성 패딩 자켓',
    price: 229000,
    modelImage: '/images/item/newitem/newitem2.png',
    itemImage: '/images/item/newitem/newitem2-1.png',
    imgHeight: 400,
  },
  {
    name: '하이랜드 남성 패딩 자켓',
    price: 229000,
    modelImage: '/images/item/newitem/newitem3.png',
    itemImage: '/images/item/newitem/newitem3-1.png',
    imgHeight: 400,
  },
  {
    name: '항공점퍼 여성 패딩 자켓',
    price: 229000,
    modelImage: '/images/item/newitem/newitem4.png',
    itemImage: '/images/item/newitem/newitem4-1.png',
    imgHeight: 400,
  },
];

export const SWIPE_JACKET = {
  categoryName: '23SS 프리미엄 고어텍스 자켓 컬렉션',
  Thumbnail: '/images/item/swiper/Jacket_thumbnail.png',
  swipeTitle: '언제 어디서나 완벽한 아웃도어룩',
  swipeHashtag: '#고어텍스 인피니엄 #쾌적함 #세련된 아웃핏',
  swipeDirection: 'row',

  item: [
    {
      name: '프리미엄 남성 고어택스 자켓',
      price: 299000,
      modelImage: '/images/item/swiper/Jacket1.png',
      itemImage: '/images/item/swiper/Jacket1-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 3L 남성 고어텍스 자켓',
      price: 379000,
      modelImage: '/images/item/swiper/Jacket2.png',
      itemImage: '/images/item/swiper/Jacket2-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 소프트 남성 고어텍스 자켓',
      price: 319000,
      modelImage: '/images/item/swiper/Jacket3.png',
      itemImage: '/images/item/swiper/Jacket3-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 남성 고어텍스 자켓',
      price: 299000,
      modelImage: '/images/item/swiper/Jacket4.png',
      itemImage: '/images/item/swiper/Jacket4-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 컬러블럭 남성 고어텍스 자켓',
      price: 299000,
      modelImage: '/images/item/swiper/Jacket5.png',
      itemImage: '/images/item/swiper/Jacket5-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 여성 고어텍스 자켓',
      price: 299000,
      modelImage: '/images/item/swiper/Jacket6.png',
      itemImage: '/images/item/swiper/Jacket6-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 소프트 여성 고어텍스 자켓',
      price: 319000,
      modelImage: '/images/item/swiper/Jacket7.png',
      itemImage: '/images/item/swiper/Jacket7-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 3L 여성 고어텍스 자켓',
      price: 379000,
      modelImage: '/images/item/swiper/Jacket8.png',
      itemImage: '/images/item/swiper/Jacket8-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '프리미엄 컬러블럭 여성 고어텍스 자켓',
      price: 299000,
      modelImage: '/images/item/swiper/Jacket9.png',
      itemImage: '/images/item/swiper/Jacket9-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
  ],
};

export const SWIPE_LIGHTWEIGHT_PUFFER = {
  categoryName: '경량 패딩 컬렉션',
  Thumbnail: '/images/item/swiper/puffer_thumbnail.png',
  swipeTitle: '지금 필요한 경량 아이템',
  swipeHashtag: '#고급스러운 디테일  #간절기 아이템 #가벼움',
  swipeDirection: 'row-reverse',

  item: [
    {
      name: '디하스 U넥 튜브 구스다운 남성 경량패딩',
      price: 199000,
      modelImage: '/images/item/swiper/puffer1.png',
      itemImage: '/images/item/swiper/puffer1-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '픽토르 U 구스다운 경량패딩',
      price: 159000,
      modelImage: '/images/item/swiper/puffer2.png',
      itemImage: '/images/item/swiper/puffer2-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '픽토르 튜브 구스다운 여성 경량패딩',
      price: 189000,
      modelImage: '/images/item/swiper/puffer3.png',
      itemImage: '/images/item/swiper/puffer3-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '픽시버G 튜브 구스다운 남성 경량패딩',
      price: 169000,
      modelImage: '/images/item/swiper/puffer4.png',
      itemImage: '/images/item/swiper/puffer4-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '픽토르 U 구스다운 경량패딩',
      price: 159000,
      modelImage: '/images/item/swiper/puffer5.png',
      itemImage: '/images/item/swiper/puffer5-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '디하스 U넥 튜브 구스다운 남성 경량패딩',
      price: 199000,
      modelImage: '/images/item/swiper/puffer6.png',
      itemImage: '/images/item/swiper/puffer6-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '디하스 U넥 튜브 구스다운 여성 경량패딩',
      price: 199000,
      modelImage: '/images/item/swiper/puffer7.png',
      itemImage: '/images/item/swiper/puffer7-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '픽토르 S 구스다운 경량패딩',
      price: 139000,
      modelImage: '/images/item/swiper/puffer8.png',
      itemImage: '/images/item/swiper/puffer8-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
    {
      name: '디하스 V넥 튜브 구스다운 남성 경량 패딩베스트',
      price: 139000,
      modelImage: '/images/item/swiper/puffer9.png',
      itemImage: '/images/item/swiper/puffer9-1.png',
      textAline: 'center',
      imgHeight: 300,
    },
  ],
};
